### ISSUE TITLE
wrong url to repository

### ISSUE THREAD

**Issue by mims92** [composer/satis#418] opened 2017-06-01 14:14 UTC
Hello,

I've successfully configured satis to get my gitlab projects on an other server.

The problem is that the URLs to the repositories are wrong...
`http://composer.xx.com/git@gitlab.xx.com:private/storage.git`

Is there a way to tell satis the correct url?

Thank you

**Comment by alcohol** [comment] 2017-06-02 06:25
Not sure I understand your full scenario or question?

**Comment by mims92** [comment] 2017-06-02 06:55
So on the Satis website were are listed my repositories, the link to them are wrong:
they lead to `http://composer.xx.com/git@gitlab.xx.com:private/storage.git` for example.
For me urls should be `https://gitlab.xxx.com/repository`.

**Comment by mims92** [comment] 2017-06-02 12:34
Ok, I found out that when using composer require ... it is working.
Although the link on my satis webpage redirect to gitlab.xx.com/git@gitlab.xx.com...

**Comment by alcohol** [comment] 2017-06-06 12:41
This is probably because of https://github.com/composer/satis/blob/master/views/package.html.twig#L86-L88

If the distUrl is in the form of `git@...` then most browsers will see that as a relative url (as in, relative to your current page). Hence why you end up with `http://.../git@...`.

**Comment by alcohol** [comment] 2017-06-06 12:43
Duplicate of #311 I just realized :-)

**Closed by alcohol** 2017-06-06 12:43 UTC
Labels: support
