### ISSUE TITLE
Virtual packages will not be found if I use providers=true in satis.json

### ISSUE THREAD

**Issue by kschroeer** [composer/satis#584] opened 2020-02-09 17:47 UTC
I have the following problem with virtual packages: I want to integrate the package geocoder-php/common-http into my application. This has the php-http/client-implementation package as a dependency, which is a virtual package. As a concrete implementation I use php-http/guzzle6-adapter. So my satis.json looks like this:

```
{
    "name": "private/repo",
    "homepage": "http://localhost",
    "repositories": [
        {
            "type": "composer",
            "url": "https://packagist.org"
        }
    ],
    "require": {
        "geocoder-php/common-http": "*",
        "php-http/guzzle6-adapter": "*"
    },
    "require-dependencies": true,
    "require-dev-dependencies": true,
    "providers": true,
    "archive": {
        "directory": "dist",
        "format": "zip",
        "skip-dev": true
    }
}
```

I run "satis build" and everything is downloaded correctly.

Now I want to use the packages in my application and have created the following composer.json:

```
{
    "name": "private/myapp",
    "type": "project",
    "repositories": [
        {
            "packagist": false
        },
        {
            "type": "composer",
            "url": "http://localhost"
        }
    ],
    "config": {
        "secure-http": false
    },
    "require": {
        "php": "^7.2",
        "geocoder-php/common-http": "^4.2",
        "php-http/guzzle6-adapter": "^2.0"
    }
}
```

If I now run a "composer install", I get the following error message:

```
  Problem 1
    - Installation request for geocoder-php/common-http ^4.2 -> satisfiable by geocoder-php/common-http[4.2.0].
    - geocoder-php/common-http 4.2.0 requires php-http/client-implementation ^1.0 -> no matching package found.
```

It seems that the guzzle6-adapter, which provides the client-implementation, is not considered at all. Is this a bug? How can I configure Satis so that the composer can find all the packages I need in my repository?

**Comment by alcohol** [comment] 2020-02-10 09:09
I was able to reproduce this using https://github.com/alcohol/satis-docker-compose-setup with your `satis.json` and `composer.json`.

Honestly, I am not sure how this is handled by https://packagist.org. So I am not sure what Satis is lacking and whether this is a bug or not (it could be this functionality was simply never implemented in Satis).

@Seldaek I know Satis is not really supported by us, but are you able to shed some light on this?

**Comment by Seldaek** [comment] 2020-02-10 11:35
Not sure why this fails in satis, AFAICT it should work, but pretty sure this will be fixed by composer v2 so probably not worth investigating further right now.

**Comment by alcohol** [comment] 2020-02-10 12:16
I think it is because https://packagist.org generates

https://packagist.org/p/php-http/client-implementation$7e1e60ce4342255217691521d182bc457bdf0f700a8e394ef2f679ad07d3093d.json (not sure how long this link will live due to the hash)

See also:
- https://packagist.org/providers/php-http/client-implementation
- https://packagist.org/providers/php-http/client-implementation.json

E.g. it knows which packages provide that implementation. 

Satis does not generate such a file.

**Comment by alcohol** [comment] 2020-02-10 13:03
Looks like a duplicate of #529 actually. Closing to keep the conversation/issue limited to a single thread.

**Closed by alcohol** 2020-02-10 13:03 UTC
Labels: bug
