### ISSUE TITLE
Regenerate index.html from packages.json

### ISSUE THREAD

**Issue by Mihailoff** [composer/satis#174] opened 2014-09-10 00:01 UTC
This goes out of standard workflow: if I make (or some tool) modifications to `packages.json` it would be nice to have separate command to regenerate `index.html`.

My use case is that I need to put *dist* section to every package that points to external location where package could be downloaded. A different tool makes this job but `index.html` remains outdated.

**Comment by alcohol** [comment] 2015-11-21 11:54
Duplicate of #94.

**Closed by alcohol** 2015-11-21 11:54 UTC
