### ISSUE TITLE
Tag a second alpha

### ISSUE THREAD

**Issue by jameshalsall** [composer/satis#344] opened 2016-07-15 08:09 UTC
Can we tag a second alpha release?

Since the first one (2 years ago) a lot has changed, specifically composer is now stable and does not work with the alpha tag we have on this repo.

**Comment by alcohol** [comment] 2016-07-15 08:11
Duplicate of #325 (sort of, though that requests a stable release).

But I can tag an alpha right now I guess, ignoring the various bugs/issues still open.

**Closed by alcohol** 2016-07-15 08:11 UTC

**Comment by alcohol** [comment] 2016-07-15 08:13
Done.

**Comment by bgaillard** [comment] 2016-07-15 08:16
:+1: agree with this. 

Why creators of satis do not create new tags and versions when they add new features ? 

I think each time a minimal set of new features and bug fixes is implemented a new tag should be created. IMO no problem if we have alpha1, alpha2 ... alpha9999999 tags.

**Comment by alcohol** [comment] 2016-07-15 08:17
It is already done. No need to add snarky comments.

**Comment by bgaillard** [comment] 2016-07-15 08:21
Hi @alcohol, thanks so much for this. 

> snarky comments

Sorry it was not my intention here, but only a suggestion to improve things and visibility associated to changes in satis for users (also as I'm French sometimes my English is not perfect and gentle enough :-)). 

Anyway thanks for this great tool, it helps us every day !

**Comment by jameshalsall** [comment] 2016-07-15 09:31
Thanks :)
