### ISSUE TITLE
Could not find package in a version matching dev-master

### ISSUE THREAD

**Issue by robineero** [composer/satis#695] opened 2022-04-04 10:26 UTC
I have been using Satis `2.0-dev` and everything works fine. No errors. Packages can be installed.

Now I needed to update it to `3.0-dev`. I use the same satis.json (with just one repository). After the successful build from `3.0-dev` I try to install the package with composer:

`composer require "vendor/packagename":"dev-master"`

I get such error:

`[InvalidArgumentException] Could not find package vendor/packagename in a version matching dev-master `

The only difference is the directory from which I run the build command (`2.0-dev` or `3.0-dev`). What might be the reason for this exception or what am I missing?

**Comment by alcohol** [comment] 2022-04-04 10:52
Possible duplicate of #664 ?

**Closed** 2022-04-04 12:54 UTC
